// Code generated by mockery v1.0.0. DO NOT EDIT.

package script

import mock "github.com/stretchr/testify/mock"
import redis "github.com/go-redis/redis"

// MockRedisClient is an autogenerated mock type for the RedisClient type
type MockRedisClient struct {
	mock.Mock
}

// Publish provides a mock function with given fields: channel, message
func (_m *MockRedisClient) Publish(channel string, message interface{}) *redis.IntCmd {
	ret := _m.Called(channel, message)

	var r0 *redis.IntCmd
	if rf, ok := ret.Get(0).(func(string, interface{}) *redis.IntCmd); ok {
		r0 = rf(channel, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.IntCmd)
		}
	}

	return r0
}
