version: '3'

services:
  app:
    privileged: true
    build: .
    image: codebox_app
    volumes:
      - .:/opt/build
      - varrun:/var/run
      - /tmp/storage:/home/codebox/storage:rshared
    depends_on:
      - dind
    environment:
      - WRAPPERPATH=/opt/build/build/codewrapper

  dind:
    privileged: true
    network_mode: host
    image: docker:18-dind
    command:
      - /scripts/dind-run.sh
    volumes:
      - varrun:/var/run
      - /tmp/storage:/home/codebox/storage:rslave
      - ./deploy/dind-run.sh:/scripts/dind-run.sh
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - IPTABLES=1
      - SETUP_FILTERING=0
      # - RUNSC_RELEASE=2018-11-22

volumes:
  varrun:
