version: '3'

services:
  app:
    privileged: true
    build: .
    image: codebox_app
    volumes:
      - .:/go/src/github.com/Syncano/codebox
      - varrun:/var/run
      - /tmp/storage:/home/codebox/storage:rshared
      - /go/src/github.com/Syncano/codebox/vendor
    depends_on:
      - dind
    environment:
      - WRAPPERPATH=/go/src/github.com/Syncano/codebox/build/codewrapper-static

  dind:
    privileged: true
    network_mode: host
    image: docker:17-dind
    command:
      - /scripts/dind-run.sh
    volumes:
      - varrun:/var/run
      - /tmp/storage:/home/codebox/storage:rslave
      - ./deploy/dind-run.sh:/scripts/dind-run.sh
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - IPTABLES=1
      - SETUP_FILTERING=0
      # - RUNSC_RELEASE=2018-11-22

volumes:
  varrun:
