version: '3'

services:
  app:
    privileged: true
    build: .
    image: codebox_app
    volumes:
      - .:/opt/build
      - varrun:/var/run
      - /tmp/storage:/home/codebox/storage:rshared
    depends_on:
      - dind
    environment:
      - WRAPPERPATH=/opt/build/build/codewrapper

  dind:
    privileged: true
    network_mode: host
    image: docker:18-dind
    command:
      - /scripts/dind-run.sh
    volumes:
      - varrun:/var/run
      - /tmp/storage:/home/codebox/storage:rslave
      - ./deploy/dind-run.sh:/scripts/dind-run.sh
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - IPTABLES=1
      - SETUP_FILTERING=0
      # - RUNSC_RELEASE=2018-11-22

  redis:
    image: redis:3.2-alpine
    volumes:
      - data-redis:/data
    ports:
      - "6379"

  rabbitmq:
    image: rabbitmq:3.8-alpine
    volumes:
      - data-rabbitmq:/data
    ports:
      - "5672"
      - "15672"

  jaeger:
    image: jaegertracing/all-in-one:1.17
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775"
      - "6831"
      - "6832"
      - "5778"
      - "16686:16686"
      - "14268:14268"
      - "14250"
      - "9411:9411"

volumes:
  varrun:
  data-rabbitmq:
  data-redis:
