[[override]]
  name = "github.com/apache/thrift"
  revision = "88591e32e710a0524327153c8b629d5b461e35e0"

[[override]]
  name = "github.com/docker/distribution"
  revision = "83389a148052d74ac602f5f1d62f86ff2f3c4aa5"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "github.com/cloudfoundry/gosigar"
  version = "1.1.0"

[[constraint]]
  name = "github.com/docker/docker"
  revision = "7195df32062bf57e9f0f86d3b03453ed0b7508b5"

[[constraint]]
  name = "github.com/emirpasic/gods"
  version = "1.12.0"

[[constraint]]
  name = "github.com/evalphobia/logrus_sentry"
  version = "0.4.6"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.14.1"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "0.3.6"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/openzipkin/zipkin-go-opentracing"
  version = "0.3.4"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0-pre1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.1.1"

[[constraint]]
  name = "github.com/smartystreets/goconvey"
  version = "1.6.3"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "1.1.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/vmihailenco/msgpack"
  version = "4.0.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.15.0"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.21.0"

[prune]
  go-tests = true
  unused-packages = true
