// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isRunRequest_Value is an autogenerated mock type for the isRunRequest_Value type
type isRunRequest_Value struct {
	mock.Mock
}

// isRunRequest_Value provides a mock function with given fields:
func (_m *isRunRequest_Value) isRunRequest_Value() {
	_m.Called()
}
