// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	logrus "github.com/sirupsen/logrus"
	mock "github.com/stretchr/testify/mock"

	script "github.com/Syncano/codebox/app/script"
)

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

// CleanupUnused provides a mock function with given fields:
func (_m *Runner) CleanupUnused() {
	_m.Called()
}

// CreatePool provides a mock function with given fields:
func (_m *Runner) CreatePool() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteContainers provides a mock function with given fields: i, id
func (_m *Runner) DeleteContainers(i *script.Index, id string) []*script.Container {
	ret := _m.Called(i, id)

	var r0 []*script.Container
	if rf, ok := ret.Get(0).(func(*script.Index, string) []*script.Container); ok {
		r0 = rf(i, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*script.Container)
		}
	}

	return r0
}

// DownloadAllImages provides a mock function with given fields:
func (_m *Runner) DownloadAllImages() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsRunning provides a mock function with given fields:
func (_m *Runner) IsRunning() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OnContainerRemoved provides a mock function with given fields: f
func (_m *Runner) OnContainerRemoved(f script.ContainerRemovedHandler) {
	_m.Called(f)
}

// Options provides a mock function with given fields:
func (_m *Runner) Options() script.Options {
	ret := _m.Called()

	var r0 script.Options
	if rf, ok := ret.Get(0).(func() script.Options); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(script.Options)
	}

	return r0
}

// Run provides a mock function with given fields: ctx, logger, requestID, def, options
func (_m *Runner) Run(ctx context.Context, logger logrus.FieldLogger, requestID string, def *script.Definition, options *script.RunOptions) (*script.Result, error) {
	ret := _m.Called(ctx, logger, requestID, def, options)

	var r0 *script.Result
	if rf, ok := ret.Get(0).(func(context.Context, logrus.FieldLogger, string, *script.Definition, *script.RunOptions) *script.Result); ok {
		r0 = rf(ctx, logger, requestID, def, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*script.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, logrus.FieldLogger, string, *script.Definition, *script.RunOptions) error); ok {
		r1 = rf(ctx, logger, requestID, def, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Shutdown provides a mock function with given fields:
func (_m *Runner) Shutdown() {
	_m.Called()
}

// StopPool provides a mock function with given fields:
func (_m *Runner) StopPool() {
	_m.Called()
}
