kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: codebox-broker
  labels:
    app: codebox
    type: broker
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: codebox
      type: broker

  template:
    metadata:
      labels:
        buildtime: ${BUILDTIME}
        app: codebox
        type: broker
    spec:
      terminationGracePeriodSeconds: 360
      imagePullSecrets:
        - name: syncano-k8s-pull-secret
      containers:
        - name: codebox-broker
          image: ${DOCKERIMAGE}:${VERSION}
          command:
            - "codebox"
            - "broker"
          resources:
            requests:
              memory: "500Mi"
              cpu: 0.5
          ports:
            - name: uwsgi
              containerPort: 8080
            - name: grpc
              containerPort: 9000
            - name: http-metrics
              containerPort: 9080
          env:
            - name: SERVICE_NAME
              value: codebox-broker
            - name: LB_ADDRS
              value: ${LB_ADDRS}
          envFrom:
            - configMapRef:
                name: codebox
            - secretRef:
                name: codebox
          livenessProbe:
            httpGet:
              path: /health
              port: 9080
            initialDelaySeconds: 5
