// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/lb/proto/workerplug.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContainerRemovedRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContainerID          string   `protobuf:"bytes,2,opt,name=containerID,proto3" json:"containerID,omitempty"`
	SourceHash           string   `protobuf:"bytes,3,opt,name=sourceHash,proto3" json:"sourceHash,omitempty"`
	Environment          string   `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	UserID               string   `protobuf:"bytes,5,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerRemovedRequest) Reset()         { *m = ContainerRemovedRequest{} }
func (m *ContainerRemovedRequest) String() string { return proto.CompactTextString(m) }
func (*ContainerRemovedRequest) ProtoMessage()    {}
func (*ContainerRemovedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d80785c52d53ac98, []int{0}
}

func (m *ContainerRemovedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerRemovedRequest.Unmarshal(m, b)
}
func (m *ContainerRemovedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerRemovedRequest.Marshal(b, m, deterministic)
}
func (m *ContainerRemovedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerRemovedRequest.Merge(m, src)
}
func (m *ContainerRemovedRequest) XXX_Size() int {
	return xxx_messageInfo_ContainerRemovedRequest.Size(m)
}
func (m *ContainerRemovedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerRemovedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerRemovedRequest proto.InternalMessageInfo

func (m *ContainerRemovedRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ContainerRemovedRequest) GetContainerID() string {
	if m != nil {
		return m.ContainerID
	}
	return ""
}

func (m *ContainerRemovedRequest) GetSourceHash() string {
	if m != nil {
		return m.SourceHash
	}
	return ""
}

func (m *ContainerRemovedRequest) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

func (m *ContainerRemovedRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type ContainerRemovedResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerRemovedResponse) Reset()         { *m = ContainerRemovedResponse{} }
func (m *ContainerRemovedResponse) String() string { return proto.CompactTextString(m) }
func (*ContainerRemovedResponse) ProtoMessage()    {}
func (*ContainerRemovedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d80785c52d53ac98, []int{1}
}

func (m *ContainerRemovedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerRemovedResponse.Unmarshal(m, b)
}
func (m *ContainerRemovedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerRemovedResponse.Marshal(b, m, deterministic)
}
func (m *ContainerRemovedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerRemovedResponse.Merge(m, src)
}
func (m *ContainerRemovedResponse) XXX_Size() int {
	return xxx_messageInfo_ContainerRemovedResponse.Size(m)
}
func (m *ContainerRemovedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerRemovedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerRemovedResponse proto.InternalMessageInfo

type RegisterRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	MCPU                 uint32   `protobuf:"varint,3,opt,name=mCPU,proto3" json:"mCPU,omitempty"`
	Memory               uint64   `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	DefaultMCPU          uint32   `protobuf:"varint,5,opt,name=defaultMCPU,proto3" json:"defaultMCPU,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d80785c52d53ac98, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *RegisterRequest) GetMCPU() uint32 {
	if m != nil {
		return m.MCPU
	}
	return 0
}

func (m *RegisterRequest) GetMemory() uint64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *RegisterRequest) GetDefaultMCPU() uint32 {
	if m != nil {
		return m.DefaultMCPU
	}
	return 0
}

type RegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d80785c52d53ac98, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

type HeartbeatRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Memory               uint64   `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d80785c52d53ac98, []int{4}
}

func (m *HeartbeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatRequest.Unmarshal(m, b)
}
func (m *HeartbeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartbeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatRequest.Merge(m, src)
}
func (m *HeartbeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartbeatRequest.Size(m)
}
func (m *HeartbeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatRequest proto.InternalMessageInfo

func (m *HeartbeatRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HeartbeatRequest) GetMemory() uint64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

type HeartbeatResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d80785c52d53ac98, []int{5}
}

func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(m, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

type DisconnectRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectRequest) Reset()         { *m = DisconnectRequest{} }
func (m *DisconnectRequest) String() string { return proto.CompactTextString(m) }
func (*DisconnectRequest) ProtoMessage()    {}
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d80785c52d53ac98, []int{6}
}

func (m *DisconnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectRequest.Unmarshal(m, b)
}
func (m *DisconnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectRequest.Marshal(b, m, deterministic)
}
func (m *DisconnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectRequest.Merge(m, src)
}
func (m *DisconnectRequest) XXX_Size() int {
	return xxx_messageInfo_DisconnectRequest.Size(m)
}
func (m *DisconnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectRequest proto.InternalMessageInfo

func (m *DisconnectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DisconnectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectResponse) Reset()         { *m = DisconnectResponse{} }
func (m *DisconnectResponse) String() string { return proto.CompactTextString(m) }
func (*DisconnectResponse) ProtoMessage()    {}
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d80785c52d53ac98, []int{7}
}

func (m *DisconnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectResponse.Unmarshal(m, b)
}
func (m *DisconnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectResponse.Marshal(b, m, deterministic)
}
func (m *DisconnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectResponse.Merge(m, src)
}
func (m *DisconnectResponse) XXX_Size() int {
	return xxx_messageInfo_DisconnectResponse.Size(m)
}
func (m *DisconnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ContainerRemovedRequest)(nil), "lb.ContainerRemovedRequest")
	proto.RegisterType((*ContainerRemovedResponse)(nil), "lb.ContainerRemovedResponse")
	proto.RegisterType((*RegisterRequest)(nil), "lb.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "lb.RegisterResponse")
	proto.RegisterType((*HeartbeatRequest)(nil), "lb.HeartbeatRequest")
	proto.RegisterType((*HeartbeatResponse)(nil), "lb.HeartbeatResponse")
	proto.RegisterType((*DisconnectRequest)(nil), "lb.DisconnectRequest")
	proto.RegisterType((*DisconnectResponse)(nil), "lb.DisconnectResponse")
}

func init() { proto.RegisterFile("pkg/lb/proto/workerplug.proto", fileDescriptor_d80785c52d53ac98) }

var fileDescriptor_d80785c52d53ac98 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4d, 0xaf, 0xd2, 0x40,
	0x14, 0x4d, 0x2b, 0x10, 0xb9, 0x06, 0x85, 0x01, 0xb1, 0xa9, 0x1f, 0x21, 0x75, 0xa1, 0x6e, 0xda,
	0x44, 0x63, 0x62, 0x74, 0x27, 0x2c, 0x70, 0x41, 0x42, 0x6a, 0x8c, 0x89, 0xbb, 0x7e, 0x5c, 0x4b,
	0x43, 0x3b, 0x53, 0x67, 0xa6, 0xf8, 0x58, 0xbf, 0xd5, 0xfb, 0x21, 0xef, 0x7f, 0xbe, 0x74, 0x5a,
	0x1e, 0xf3, 0x0a, 0xac, 0x98, 0x39, 0xf7, 0x9c, 0x73, 0xcf, 0xbd, 0x4c, 0xe1, 0x75, 0xb1, 0x4d,
	0xbc, 0x2c, 0xf4, 0x0a, 0xce, 0x24, 0xf3, 0xfe, 0x33, 0xbe, 0x45, 0x5e, 0x64, 0x65, 0xe2, 0x2a,
	0x80, 0x98, 0x59, 0xe8, 0xdc, 0x1a, 0xf0, 0x62, 0xce, 0xa8, 0x0c, 0x52, 0x8a, 0xdc, 0xc7, 0x9c,
	0xed, 0x30, 0xf6, 0xf1, 0x5f, 0x89, 0x42, 0x92, 0xa7, 0x60, 0xa6, 0xb1, 0x65, 0xcc, 0x8c, 0xf7,
	0x7d, 0xdf, 0x4c, 0x63, 0x32, 0x83, 0x27, 0xd1, 0x81, 0xfa, 0x63, 0x61, 0x99, 0xaa, 0xa0, 0x43,
	0xe4, 0x0d, 0x80, 0x60, 0x25, 0x8f, 0x70, 0x19, 0x88, 0x8d, 0xf5, 0x48, 0x11, 0x34, 0xa4, 0x72,
	0x40, 0xba, 0x4b, 0x39, 0xa3, 0x39, 0x52, 0x69, 0x75, 0x6a, 0x07, 0x0d, 0x22, 0x53, 0xe8, 0x95,
	0x42, 0xd9, 0x77, 0x55, 0xb1, 0xb9, 0x39, 0x36, 0x58, 0xa7, 0x31, 0x45, 0xc1, 0xa8, 0x40, 0xe7,
	0xda, 0x80, 0x67, 0x3e, 0x26, 0xa9, 0x90, 0x55, 0xed, 0x7c, 0x76, 0x02, 0x9d, 0x82, 0x71, 0xa9,
	0x42, 0x0f, 0x7c, 0x75, 0xae, 0xb0, 0x7c, 0xbe, 0xfe, 0xa5, 0x72, 0x0e, 0x7c, 0x75, 0xae, 0xfa,
	0xe7, 0x98, 0x33, 0xbe, 0x57, 0xe1, 0x3a, 0x7e, 0x73, 0xab, 0x92, 0xc7, 0xf8, 0x37, 0x28, 0x33,
	0xb9, 0xaa, 0x24, 0x5d, 0x25, 0xd1, 0x21, 0x87, 0xc0, 0xf0, 0x18, 0xa2, 0x49, 0xf6, 0x15, 0x86,
	0x4b, 0x0c, 0xb8, 0x0c, 0x31, 0x90, 0x97, 0x92, 0x1d, 0x3b, 0x9a, 0x7a, 0x47, 0x67, 0x0c, 0x23,
	0x4d, 0xdb, 0x18, 0xbe, 0x85, 0xd1, 0x22, 0x15, 0x11, 0xa3, 0x14, 0xa3, 0x4b, 0x8e, 0xce, 0x04,
	0x88, 0x4e, 0xaa, 0xa5, 0x1f, 0x6f, 0x4c, 0x80, 0xdf, 0xea, 0x09, 0xac, 0xb3, 0x32, 0x21, 0x2b,
	0x18, 0xb6, 0x17, 0x4a, 0x5e, 0xba, 0x59, 0xe8, 0x5e, 0x78, 0x0d, 0xf6, 0xab, 0xf3, 0xc5, 0xda,
	0x9d, 0x7c, 0x86, 0xc7, 0x87, 0xe9, 0xc9, 0xb8, 0x62, 0xb6, 0xfe, 0x10, 0x7b, 0xf2, 0x10, 0x6c,
	0x64, 0x5f, 0xa0, 0x7f, 0x3f, 0x24, 0x51, 0x94, 0xf6, 0xbe, 0xec, 0xe7, 0x2d, 0xb4, 0x51, 0x7e,
	0x03, 0x38, 0x0e, 0x49, 0x14, 0xe9, 0x64, 0x33, 0xf6, 0xb4, 0x0d, 0xd7, 0xe2, 0xef, 0x1f, 0xfe,
	0xbc, 0x4b, 0x52, 0xb9, 0x29, 0x43, 0x37, 0x62, 0xb9, 0xf7, 0x73, 0x4f, 0xa3, 0x80, 0x32, 0x2f,
	0x62, 0x31, 0x86, 0xec, 0xca, 0xd3, 0xbf, 0x9a, 0xb0, 0xa7, 0x7e, 0x3e, 0xdd, 0x05, 0x00, 0x00,
	0xff, 0xff, 0x56, 0xe7, 0xd8, 0xae, 0x4c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkerPlugClient is the client API for WorkerPlug service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkerPlugClient interface {
	// ContainerRemoved handles notifications sent by client whenever a container gets removed from cache.
	ContainerRemoved(ctx context.Context, in *ContainerRemovedRequest, opts ...grpc.CallOption) (*ContainerRemovedResponse, error)
	// Register is sent at the beginning by the worker.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat is meant to be called periodically by worker. If it's not sent for some time, worker will be removed.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Disconnect gracefully removes worker.
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
}

type workerPlugClient struct {
	cc *grpc.ClientConn
}

func NewWorkerPlugClient(cc *grpc.ClientConn) WorkerPlugClient {
	return &workerPlugClient{cc}
}

func (c *workerPlugClient) ContainerRemoved(ctx context.Context, in *ContainerRemovedRequest, opts ...grpc.CallOption) (*ContainerRemovedResponse, error) {
	out := new(ContainerRemovedResponse)
	err := c.cc.Invoke(ctx, "/lb.WorkerPlug/ContainerRemoved", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerPlugClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/lb.WorkerPlug/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerPlugClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/lb.WorkerPlug/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerPlugClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, "/lb.WorkerPlug/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerPlugServer is the server API for WorkerPlug service.
type WorkerPlugServer interface {
	// ContainerRemoved handles notifications sent by client whenever a container gets removed from cache.
	ContainerRemoved(context.Context, *ContainerRemovedRequest) (*ContainerRemovedResponse, error)
	// Register is sent at the beginning by the worker.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat is meant to be called periodically by worker. If it's not sent for some time, worker will be removed.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Disconnect gracefully removes worker.
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
}

func RegisterWorkerPlugServer(s *grpc.Server, srv WorkerPlugServer) {
	s.RegisterService(&_WorkerPlug_serviceDesc, srv)
}

func _WorkerPlug_ContainerRemoved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerRemovedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerPlugServer).ContainerRemoved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.WorkerPlug/ContainerRemoved",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerPlugServer).ContainerRemoved(ctx, req.(*ContainerRemovedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerPlug_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerPlugServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.WorkerPlug/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerPlugServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerPlug_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerPlugServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.WorkerPlug/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerPlugServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerPlug_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerPlugServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lb.WorkerPlug/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerPlugServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkerPlug_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lb.WorkerPlug",
	HandlerType: (*WorkerPlugServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ContainerRemoved",
			Handler:    _WorkerPlug_ContainerRemoved_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _WorkerPlug_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _WorkerPlug_Heartbeat_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _WorkerPlug_Disconnect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/lb/proto/workerplug.proto",
}
