// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isUploadRequest_Value is an autogenerated mock type for the isUploadRequest_Value type
type isUploadRequest_Value struct {
	mock.Mock
}

// isUploadRequest_Value provides a mock function with given fields:
func (_m *isUploadRequest_Value) isUploadRequest_Value() {
	_m.Called()
}
