// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/filerepo/proto/repo.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExistsRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistsRequest) Reset()         { *m = ExistsRequest{} }
func (m *ExistsRequest) String() string { return proto.CompactTextString(m) }
func (*ExistsRequest) ProtoMessage()    {}
func (*ExistsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a71a9e5b1677d47, []int{0}
}

func (m *ExistsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistsRequest.Unmarshal(m, b)
}
func (m *ExistsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistsRequest.Marshal(b, m, deterministic)
}
func (m *ExistsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistsRequest.Merge(m, src)
}
func (m *ExistsRequest) XXX_Size() int {
	return xxx_messageInfo_ExistsRequest.Size(m)
}
func (m *ExistsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExistsRequest proto.InternalMessageInfo

func (m *ExistsRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ExistsResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistsResponse) Reset()         { *m = ExistsResponse{} }
func (m *ExistsResponse) String() string { return proto.CompactTextString(m) }
func (*ExistsResponse) ProtoMessage()    {}
func (*ExistsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a71a9e5b1677d47, []int{1}
}

func (m *ExistsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistsResponse.Unmarshal(m, b)
}
func (m *ExistsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistsResponse.Marshal(b, m, deterministic)
}
func (m *ExistsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistsResponse.Merge(m, src)
}
func (m *ExistsResponse) XXX_Size() int {
	return xxx_messageInfo_ExistsResponse.Size(m)
}
func (m *ExistsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExistsResponse proto.InternalMessageInfo

func (m *ExistsResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type UploadRequest struct {
	// Types that are valid to be assigned to Value:
	//	*UploadRequest_Meta
	//	*UploadRequest_Chunk
	//	*UploadRequest_Done
	Value                isUploadRequest_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a71a9e5b1677d47, []int{2}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

type isUploadRequest_Value interface {
	isUploadRequest_Value()
}

type UploadRequest_Meta struct {
	Meta *UploadRequest_MetaMessage `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type UploadRequest_Chunk struct {
	Chunk *UploadRequest_ChunkMessage `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type UploadRequest_Done struct {
	Done bool `protobuf:"varint,3,opt,name=done,proto3,oneof"`
}

func (*UploadRequest_Meta) isUploadRequest_Value() {}

func (*UploadRequest_Chunk) isUploadRequest_Value() {}

func (*UploadRequest_Done) isUploadRequest_Value() {}

func (m *UploadRequest) GetValue() isUploadRequest_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *UploadRequest) GetMeta() *UploadRequest_MetaMessage {
	if x, ok := m.GetValue().(*UploadRequest_Meta); ok {
		return x.Meta
	}
	return nil
}

func (m *UploadRequest) GetChunk() *UploadRequest_ChunkMessage {
	if x, ok := m.GetValue().(*UploadRequest_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (m *UploadRequest) GetDone() bool {
	if x, ok := m.GetValue().(*UploadRequest_Done); ok {
		return x.Done
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UploadRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UploadRequest_Meta)(nil),
		(*UploadRequest_Chunk)(nil),
		(*UploadRequest_Done)(nil),
	}
}

type UploadRequest_MetaMessage struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest_MetaMessage) Reset()         { *m = UploadRequest_MetaMessage{} }
func (m *UploadRequest_MetaMessage) String() string { return proto.CompactTextString(m) }
func (*UploadRequest_MetaMessage) ProtoMessage()    {}
func (*UploadRequest_MetaMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a71a9e5b1677d47, []int{2, 0}
}

func (m *UploadRequest_MetaMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest_MetaMessage.Unmarshal(m, b)
}
func (m *UploadRequest_MetaMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest_MetaMessage.Marshal(b, m, deterministic)
}
func (m *UploadRequest_MetaMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest_MetaMessage.Merge(m, src)
}
func (m *UploadRequest_MetaMessage) XXX_Size() int {
	return xxx_messageInfo_UploadRequest_MetaMessage.Size(m)
}
func (m *UploadRequest_MetaMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest_MetaMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest_MetaMessage proto.InternalMessageInfo

func (m *UploadRequest_MetaMessage) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type UploadRequest_ChunkMessage struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest_ChunkMessage) Reset()         { *m = UploadRequest_ChunkMessage{} }
func (m *UploadRequest_ChunkMessage) String() string { return proto.CompactTextString(m) }
func (*UploadRequest_ChunkMessage) ProtoMessage()    {}
func (*UploadRequest_ChunkMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a71a9e5b1677d47, []int{2, 1}
}

func (m *UploadRequest_ChunkMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest_ChunkMessage.Unmarshal(m, b)
}
func (m *UploadRequest_ChunkMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest_ChunkMessage.Marshal(b, m, deterministic)
}
func (m *UploadRequest_ChunkMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest_ChunkMessage.Merge(m, src)
}
func (m *UploadRequest_ChunkMessage) XXX_Size() int {
	return xxx_messageInfo_UploadRequest_ChunkMessage.Size(m)
}
func (m *UploadRequest_ChunkMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest_ChunkMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest_ChunkMessage proto.InternalMessageInfo

func (m *UploadRequest_ChunkMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UploadRequest_ChunkMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type UploadResponse struct {
	Accepted             bool     `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a71a9e5b1677d47, []int{3}
}

func (m *UploadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadResponse.Unmarshal(m, b)
}
func (m *UploadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadResponse.Marshal(b, m, deterministic)
}
func (m *UploadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadResponse.Merge(m, src)
}
func (m *UploadResponse) XXX_Size() int {
	return xxx_messageInfo_UploadResponse.Size(m)
}
func (m *UploadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadResponse proto.InternalMessageInfo

func (m *UploadResponse) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func init() {
	proto.RegisterType((*ExistsRequest)(nil), "repo.ExistsRequest")
	proto.RegisterType((*ExistsResponse)(nil), "repo.ExistsResponse")
	proto.RegisterType((*UploadRequest)(nil), "repo.UploadRequest")
	proto.RegisterType((*UploadRequest_MetaMessage)(nil), "repo.UploadRequest.MetaMessage")
	proto.RegisterType((*UploadRequest_ChunkMessage)(nil), "repo.UploadRequest.ChunkMessage")
	proto.RegisterType((*UploadResponse)(nil), "repo.UploadResponse")
}

func init() { proto.RegisterFile("pkg/filerepo/proto/repo.proto", fileDescriptor_4a71a9e5b1677d47) }

var fileDescriptor_4a71a9e5b1677d47 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x6f, 0xea, 0x30,
	0x10, 0x7c, 0x81, 0xc0, 0xe3, 0x2d, 0x1f, 0x7a, 0x72, 0x39, 0xa0, 0x48, 0x15, 0x34, 0x27, 0x0e,
	0x6d, 0x5c, 0x81, 0xfa, 0x71, 0xa6, 0xaa, 0xd4, 0x0b, 0x97, 0x54, 0xbd, 0xf4, 0x66, 0x92, 0x2d,
	0xa0, 0x40, 0xd6, 0xc5, 0x4e, 0x05, 0xff, 0xbc, 0xc7, 0xca, 0x4e, 0xd2, 0x12, 0xd1, 0x53, 0xc6,
	0xd6, 0xcc, 0xec, 0xec, 0xc4, 0x70, 0x2e, 0x93, 0x25, 0x7f, 0x5b, 0x6f, 0x70, 0x87, 0x92, 0xb8,
	0xdc, 0x91, 0x26, 0x6e, 0x60, 0x60, 0x21, 0x73, 0x0d, 0xf6, 0x2f, 0xa0, 0xfb, 0xb8, 0x5f, 0x2b,
	0xad, 0x42, 0x7c, 0xcf, 0x50, 0x69, 0xf6, 0x1f, 0xea, 0x09, 0x1e, 0x06, 0xce, 0xc8, 0x19, 0xff,
	0x0b, 0x0d, 0xf4, 0x47, 0xd0, 0x2b, 0x29, 0x4a, 0x52, 0xaa, 0x90, 0xf5, 0xa0, 0x46, 0x89, 0xa5,
	0xb4, 0xc2, 0x1a, 0x25, 0xfe, 0xa7, 0x03, 0xdd, 0x17, 0xb9, 0x21, 0x11, 0x97, 0x2e, 0x37, 0xe0,
	0x6e, 0x51, 0x0b, 0xcb, 0x69, 0x4f, 0x86, 0x81, 0x9d, 0x5b, 0xa1, 0x04, 0x73, 0xd4, 0x62, 0x8e,
	0x4a, 0x89, 0x25, 0x3e, 0xfd, 0x09, 0x2d, 0x9d, 0xdd, 0x43, 0x23, 0x5a, 0x65, 0x69, 0x32, 0xa8,
	0x59, 0xdd, 0xe8, 0x37, 0xdd, 0x83, 0x21, 0xfc, 0x08, 0x73, 0x01, 0xeb, 0x83, 0x1b, 0x53, 0x8a,
	0x83, 0xba, 0x09, 0x65, 0xfc, 0xcc, 0xc9, 0x1b, 0x42, 0xfb, 0x68, 0xcc, 0xe9, 0x6e, 0xde, 0x2d,
	0x74, 0x8e, 0xfd, 0x18, 0x03, 0x37, 0x15, 0x5b, 0x2c, 0x28, 0x16, 0x9b, 0xbb, 0x58, 0x68, 0x61,
	0x33, 0x75, 0x42, 0x8b, 0x67, 0x7f, 0xa1, 0xf1, 0x21, 0x36, 0x19, 0xfa, 0x97, 0xd0, 0x2b, 0xe3,
	0x15, 0xe5, 0x78, 0xd0, 0x12, 0x51, 0x84, 0x52, 0x63, 0x5c, 0x54, 0xf4, 0x7d, 0x9e, 0x68, 0x70,
	0x43, 0x94, 0xc4, 0xa6, 0xd0, 0xcc, 0x2b, 0x65, 0x67, 0xf9, 0x8a, 0x95, 0x7f, 0xe0, 0xf5, 0xab,
	0x97, 0x85, 0xf1, 0x1d, 0x34, 0xf3, 0x51, 0xa5, 0xa8, 0xd2, 0x4b, 0x29, 0xaa, 0xa6, 0x19, 0x3b,
	0xd7, 0xce, 0x8c, 0xbf, 0x5e, 0x2d, 0xd7, 0x7a, 0x95, 0x2d, 0x82, 0x88, 0xb6, 0xfc, 0xf9, 0x90,
	0x46, 0x22, 0x25, 0x1e, 0x51, 0x8c, 0x0b, 0xda, 0xf3, 0xd3, 0x57, 0xb2, 0x68, 0xda, 0xcf, 0xf4,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x4e, 0x17, 0x2d, 0x42, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RepoClient is the client API for Repo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RepoClient interface {
	// Exists checks if file was defined in file repo.
	Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error)
	// Upload streams file(s) to server.
	Upload(ctx context.Context, opts ...grpc.CallOption) (Repo_UploadClient, error)
}

type repoClient struct {
	cc *grpc.ClientConn
}

func NewRepoClient(cc *grpc.ClientConn) RepoClient {
	return &repoClient{cc}
}

func (c *repoClient) Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error) {
	out := new(ExistsResponse)
	err := c.cc.Invoke(ctx, "/repo.Repo/Exists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repoClient) Upload(ctx context.Context, opts ...grpc.CallOption) (Repo_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Repo_serviceDesc.Streams[0], "/repo.Repo/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &repoUploadClient{stream}
	return x, nil
}

type Repo_UploadClient interface {
	Send(*UploadRequest) error
	Recv() (*UploadResponse, error)
	grpc.ClientStream
}

type repoUploadClient struct {
	grpc.ClientStream
}

func (x *repoUploadClient) Send(m *UploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *repoUploadClient) Recv() (*UploadResponse, error) {
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RepoServer is the server API for Repo service.
type RepoServer interface {
	// Exists checks if file was defined in file repo.
	Exists(context.Context, *ExistsRequest) (*ExistsResponse, error)
	// Upload streams file(s) to server.
	Upload(Repo_UploadServer) error
}

func RegisterRepoServer(s *grpc.Server, srv RepoServer) {
	s.RegisterService(&_Repo_serviceDesc, srv)
}

func _Repo_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepoServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repo.Repo/Exists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepoServer).Exists(ctx, req.(*ExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repo_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RepoServer).Upload(&repoUploadServer{stream})
}

type Repo_UploadServer interface {
	Send(*UploadResponse) error
	Recv() (*UploadRequest, error)
	grpc.ServerStream
}

type repoUploadServer struct {
	grpc.ServerStream
}

func (x *repoUploadServer) Send(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *repoUploadServer) Recv() (*UploadRequest, error) {
	m := new(UploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Repo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "repo.Repo",
	HandlerType: (*RepoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exists",
			Handler:    _Repo_Exists_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _Repo_Upload_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/filerepo/proto/repo.proto",
}
