// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SystemChecker is an autogenerated mock type for the SystemChecker type
type SystemChecker struct {
	mock.Mock
}

// AvailableMemory provides a mock function with given fields:
func (_m *SystemChecker) AvailableMemory() uint64 {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// CheckFreeMemory provides a mock function with given fields: want
func (_m *SystemChecker) CheckFreeMemory(want uint64) error {
	ret := _m.Called(want)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(want)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FreeMemory provides a mock function with given fields: amount
func (_m *SystemChecker) FreeMemory(amount uint64) {
	_m.Called(amount)
}

// GetDiskUsage provides a mock function with given fields: path
func (_m *SystemChecker) GetDiskUsage(path string) (float64, uint64) {
	ret := _m.Called(path)

	var r0 float64
	if rf, ok := ret.Get(0).(func(string) float64); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 uint64
	if rf, ok := ret.Get(1).(func(string) uint64); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	return r0, r1
}

// GetMemory provides a mock function with given fields:
func (_m *SystemChecker) GetMemory() (uint64, uint64) {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	var r1 uint64
	if rf, ok := ret.Get(1).(func() uint64); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(uint64)
	}

	return r0, r1
}

// ReserveMemory provides a mock function with given fields: amount
func (_m *SystemChecker) ReserveMemory(amount uint64) error {
	ret := _m.Called(amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reset provides a mock function with given fields:
func (_m *SystemChecker) Reset() {
	_m.Called()
}
